#!/usr/bin/python
#
# creates a "message hub" that nodes can use to communicate with each other
# It creates 8 endpoints for nodes to connect to - e.g. node <i> makes
# a SEQPACKET connection to the address '\0<name>.bus.<i>' where <name> is your 
# username
#
# You can't run multiple copies of this program on the same machine under the same
# user ID, or else they'll try to use the same addresses.
#

import sys
import threading
import socket
import argparse
import select
import string
import getpass

parser = argparse.ArgumentParser(description='Bus - project 5 message bus')
parser.add_argument('--verbose', action='store_true', help='print transmitted messages')
parser.add_argument('--quiet', action='store_true', help='don\'t print anything')
args = parser.parse_args()

sockets = [None] * 8
socket_map = dict()

def print_msg(f, t, msg):
    for line in msg.split('\n'):
        print f, '->', t, line

# a single endpoint - accept connections on "bus.#", and forward packets between
# connections. Runs as a separate thread.
#
def transfer(i):
    global sockets
    
    ls = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
    ls.bind('\0%s.bus.%d' % (getpass.getuser(), i))
    ls.listen(2)
    
    while True:
        s,addr = ls.accept()
        print 'connection on %d' % i
        sockets[i] = s
        while True:
            dgram = None
            try:
                dgram = s.recv(4096)
            except:
                pass

            if not dgram or not dgram.startswith('To: '):
                s.close()
                sockets[i] = None
                break
            
            d = dict([line.split(': ') for line in dgram.split('\n')])
            t,id = int(d['To']),int(d['Id'])
            if args.verbose:
                print_msg(i, t, dgram)
            if t < 8:
                sockets[t].send(dgram)
            elif id in socket_map:
                    socket_map[id].send(dgram)
                    socket_map[id].close()
                    del socket_map[id]

client_sockets = []

def client_transfer():
    global sockets
    ls = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
    my_sockets = []
    ls.bind('\0%s.bus.%d' % (getpass.getuser(), 8))
    ls.listen(2)

    while True:
        ready, ignore1, ignore2 = select.select(my_sockets + [socket_map[i] for i in socket_map] + [ls], (), ())
        for r in ready:
            if r == ls:
                s2,addr = r.accept()
                my_sockets.append(s2)
                if not args.quiet:
                    print 'connection from', addr
            else:
                try:
                    dgram = r.recv(4096)
                except:
                    dgram = None
                if not dgram or not dgram.startswith('To: '):
                    if r in client_sockets:
                        client_sockets.remove(r)
                    if r in socket_map:
                        del socket_map[r]
                    r.close()
                    continue

                # forward from client to a node, leave map entry for reply
                d = dict([line.split(': ') for line in dgram.split('\n')])
                t = int(d['To'])
                if args.verbose:
                    print_msg(8, t, dgram)

                if 0 <= t < 8 and sockets[t]:
                    socket_map[int(d['Id'])] = r
                    sockets[t].send(dgram)
                else:
                    r.close()
                my_sockets.remove(r)

def start_thread(function, i):
    t = threading.Thread(target=function, args=[i])
    t.daemon = True
    t.start()
    
def run_bus():
    # start the receivers
    #
    [start_thread(transfer, i) for i in range(8)]

    client_transfer()

if __name__ == '__main__':
    run_bus()
