#!/usr/bin/python

import sys
import socket
import time
import threading
import string
import getpass
import argparse

parser = argparse.ArgumentParser(description='example - send messages on message bus')
parser.add_argument('nodeid', metavar='n', type=int, nargs=1, help='Node ID')

args = parser.parse_args()
nodeid = args.nodeid[0]

keys = dict()
cmdarr = Queue.Queue()
okarr = Queue.Queue()
cachedict = dict()
ackdict = dict()

#TODO: 1s Timeout for cachedict & ackdict



"""
parsepkt
args: pkt
return: List
description: parses out a packet into List of fields 
"""
def parsepkt(package): 
    pkt = package.split('\n')[:6]
    pkt = map(lambda x: x.split(': ')[1], pkt)
    return pkt


"""
hash2node
args: key
return: n
description: hashes a key
"""
def hash2node(key):
    h = sum(map(lambda x: int(ord(x)), list(key)))%255
    n = int(h/0x20)
    return n 

"""
mkpkt
args: To, From, Cmd, Id, Key, Value
return: String 
description: Takes input and formats a packet
"""
def mkpkt(To, From, Cmd, Id, Key, Value):
    pkt = "To: %d\nFrom: %d\nCmd: %d\nId: %d\nKey: %d\nValue: %d\n" % (To, From, Cmd, Id, Key, Value)
    return pkt


"""
putqueue
args: pkt
return: none
description: Puts pkt into either okarr or cmdarr
"""
def putqueue(pkt):
    if (parsepkt(pkt)[2] == 'ok'):
        okarr.put(pkt)
    else:
        cmdarr.put(pkt)


"""
"""
def processok(pkt):
    To = parsepkt(pkt)[0]
    From = parsepkt(pkt)[1]
    Cmd = parsepkt(pkt)[2]
    Id = parsepkt(pkt)[3]
    Key = parsepkt(pkt)[4]
    Value = parsepkt(pkt)[5]

    # FOUND
        # SEND 'cmd:ok'
    # ELSE



"""
protocolop
args: pkt, nodeid, s
return: null
description: Performs cmd operations
"""
def protocolop(pkt, s):
    
    To = parsepkt(pkt)[0]
    From = parsepkt(pkt)[1]
    Cmd = parsepkt(pkt)[2]
    Id = parsepkt(pkt)[3]
    Key = parsepkt(pkt)[4]
    Value = parsepkt(pkt)[5]
    
    n = hash2node(key)
    

    if (cmd == 'put'):
        # Send 'store' message to each node n, n+1, n+2
        # Use correct ID field 
        for i in range(0, 3):
            pkt = mkpkt(n+i, nodeid, 'store',seq, Key, Value) 
            cachedict[Id] = pkt
            s.send(pkt)

        # return 'cmd: ok' to client if get reply from one
        # If all three nodes don't reply (within 1s each), reply 'cmd:fail' to client

    elif (cmd == 'store'):
        keys[Key] = Value  # store key/value pair in internal database
        s.send(mkpkt(From, nodeid, 'ok', seq, Key, Value)) # return 'cmd:ok'
        

    elif (cmd == 'get'):
        # Send 'fetch' to nodes n, n+1, n+2
        for i in range(0,3):
            pkt = mkpkt(n+i, nodeid, 'fetch', seq, Key, Value)
            cachedict[Id] = pkt
            s.send(pkt)
        
        # return 'cmd:ok' if one replies (appropriate 'id', 'key', and 'value'
        # else return 'cmd:fail' 
    elif (cmd == 'fetch'):
        # look up requested key and return it in a 'cmd:ok' message
        if Key in keys:
            s.send(mkpkt(From, nodeid, 'ok', seq, Key, keys[Key]))
        # else return 'cmd: fail'
            s.send(mkpkt(From, nodeid, 'fail', seq, Key, Value))
    elif (cmd == 'reload'):
        # send a 'cmd:store' with every key in internal database to send node n
        for key in keys.keys():
            pkt = mkpkt(n, nodeid, 'store', seq, key, keys[key])
            cachedict[Id] = pkt
            s.send(pkt)
        # wait for reply 
    else:


def receive(s):
    while True:
        dgram = s.recv(4096)
        if not dgram:
            print 'lost connection'
            sys.exit(1)

        putqueue(dgram) # separates packages into okarr and cmdarr

if __name__ == '__main__':
    s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
    s.bind('\0%s.test-%d' % (getpass.getuser(), nodeid))
    if s.connect_ex('\0%s.bus.%d' % (getpass.getuser(), nodeid)):
        print 'connection error'
        sys.exit(1)

    t = threading.Thread(target = receive, args=[s])
    t.daemon = True
    t.start()

    seq = 0
    while True:
        for i in range(9):
            time.sleep(1)
            pkt = "To: %d\nFrom: %d\nCmd: test\nId: %d\nKey: \nValue: \n" % (i, nodeid, seq)
            s.send(pkt)
            seq += 1

